
package de.jevenari.sw.service;

import javax.xml.ws.WebFault;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.3.1-SNAPSHOT
 * Generated source version: 2.2
 * 
 */
@WebFault(name = "BankingException", targetNamespace = "http://service.sw.jevenari.de/")
public class BankingException_Exception
    extends Exception
{

    /**
     * Java type that goes as soapenv:Fault detail element.
     * 
     */
    private BankingException faultInfo;

    /**
     * 
     * @param faultInfo
     * @param message
     */
    public BankingException_Exception(String message, BankingException faultInfo) {
        super(message);
        this.faultInfo = faultInfo;
    }

    /**
     * 
     * @param faultInfo
     * @param cause
     * @param message
     */
    public BankingException_Exception(String message, BankingException faultInfo, Throwable cause) {
        super(message, cause);
        this.faultInfo = faultInfo;
    }

    /**
     * 
     * @return
     *     returns fault bean: de.jevenari.sw.service.BankingException
     */
    public BankingException getFaultInfo() {
        return faultInfo;
    }

}
